routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController')->middleware(['role:superadministrator']);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
    Route::get('map', function () {return view('pages.maps');})->name('map');
    Route::get('icons', function () {return view('pages.icons');})->name('icons');
    Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::resource("project","App\Http\Controllers\ProjectController");
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Project extends Model
{
    use HasFactory;
    protected $table="projects";
    protected $fillable=[
        "name",
        "desc",
        "url",
        "status",
        "user_id",
    ];
    const FILES_PATH_BASE="Project";
    const STATUS=['active'=>'active', 'incomplete'=>'incomplete', 'ongoing'=> 'ongoing','stuck'=>'stuck'];
    public function files(){
        return $this->morphMany(File::class,"fileable");
    }
    public function image(){
        return $this->files()->where("mime","image")->first();
    }
    public function video(){
        return $this->files()->where("mime","video")->first();
    }
    public function doc(){
        return $this->files()->where("mime","doc")->first();
    }
    public function user(){
        return $this->belongsTo(File::class,"user_id");
    }
    public static function files_attach($request,$project=null,$update=false){

        if($request->has("image") && !is_null($request->image)){
            upload_file($request->file('image'),Project::FILES_PATH_BASE,$project,'image');
            if($update){
                delete_file($project->image());
            }

        }
        if($request->has("video") && !is_null($request->video)){
            upload_file($request->file('video'),Project::FILES_PATH_BASE,$project,'video');
            if($update){
                delete_file($project->video());
            }
        }
        if($request->has("doc") && !is_null($request->doc)){
            upload_file($request->file('doc'),Project::FILES_PATH_BASE,$project,'doc');
            if($update){
                delete_file($project->doc());
            }
        }
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use App\DataTables\ProjectDatatable;
use App\Http\Requests\StoreProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Models\File;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()

    {
        $this->authorizeResource(Project::class, 'project');
    }
    public function index(ProjectDatatable $project)
    {

        $title=__('Project Management');
        return  $project->render("projects.index",compact("title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title=__('Create Project');
        $status=Project::STATUS;
        return view("projects.create",compact("title","status"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProjectRequest $request)
    {
        $request->validated();
        $project=Project::create(array_merge(["user_id"=>auth()->id()],$request->all()));
        Project::files_attach($request,$project);
        session()->flash('created',__("Changes has been Created successfully"));
        if(auth()->user()->hasRole("user")){
            return redirect()->to(route("project.index")."?user=".auth()->id());
        }
        return redirect()->route("project.index");
    }

/**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {

        $title=__('Show Project');
        $status=Project::STATUS;
        return view("projects.show",compact("project",'status'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $title=__('Edit Project');
        $status=Project::STATUS;
        return view("projects.edit",compact("project",'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProjectRequest $request, Project $project)
    {
        $request->validated();
        $project->update($request->all());
        Project::files_attach($request,$project,true);
        session()->flash('created',__("Changes has been Updated successfully"));
        if(auth()->user()->hasRole("user")){
            return redirect()->to(route("project.index")."?user=".auth()->id());
        }
        return redirect()->route("project.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        foreach($project->files as $file){
            delete_file($file);
            $file->delete();
        }
        $project->delete();
        session()->flash('deleted',__("Changes has been Deleted successfully"));
        return redirect()->route("project.index");
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app', ['title' => $title ?? ''])

@section('content')

<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
</div>


<div class="container-fluid mt--7">
        <div class="card bg-secondary shadow">
            <div class="kt-portlet__body">
                {!! Form::open(['route'=>'project.store', 'method'=>'post', 'class'=>'kt-form kt-form--labe-right','files'=>true]) !!}
                    <div class="kt-portlet__head kt-portlet__head--lg">
                        @include("layouts.includes.form_button",['disabled'=>false,"route"=>"project"])
                    </div>
                    @include('projects.form', ['disabled'=>false,'preview'=>false])
                {!! Form::close() !!}
            </div>
        </div>
</div>


@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app', ['title' => $title ?? ''])

@section('content')

<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
</div>

<div class="container-fluid mt--7">
    <div class="card bg-secondary shadow">
        <div class="kt-portlet__body">
            {!! Form::model($project,['route'=>['project.update', $project->id], 'method'=>'patch','class'=>'kt-form kt-form--labe-right','id'=>'kt_form','files'=>true]) !!}
            <div class="kt-portlet__head kt-portlet__head--lg">
                @include("layouts.includes.form_button",['disabled'=>false,"route"=>"project"])
            </div>
                @include('projects.form', ['disabled'=>false,'preview'=>true])
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/projects/form.blade.php
<div class="container mt-3">
    <div class="form-group row">
        <div class="col-lg-6">
            <label>{{__('Name')}}<span class="text-danger">*</span></label>
            {!! Form::text('name', null, ['class'=>'form-control', 'disabled'=>$disabled]) !!}
            @if ($errors->has("name"))
                <span class="form-text text-danger">{{$errors->first('name')}}</span>
            @endif
        </div>
        <div class="col-lg-6">
            <label>{{__('Description')}}<span class="text-danger">*</span></label>
            {!! Form::text('desc', null, ['class'=>'form-control', 'disabled'=>$disabled]) !!}
            @if ($errors->has("desc"))
                <span class="form-text text-danger">{{$errors->first('desc')}}</span>
            @endif
        </div>
        <div class="col-lg-6">
            <label>{{__('Project URL')}}<span class="text-danger">*</span></label>
            {!! Form::text('url', null, ['class'=>'form-control', 'disabled'=>$disabled]) !!}
            @if ($errors->has("url"))
                <span class="form-text text-danger">{{$errors->first('url')}}</span>
            @endif
        </div>
        <div class="col-lg-6">
            <label>{{__('Status')}}<span class="text-danger">*</span></label>
            {!! Form::select('status', $status,null, ['class'=>'form-control','placeholder'=>"Select status" ,'disabled'=>$disabled]) !!}
            @if ($errors->has("status"))
                <span class="form-text text-danger">{{$errors->first('status')}}</span>
            @endif
        </div>
        @if(!$disabled)
            <div class="col-lg-6">
                <label>{{__('Image')}} @if(!$preview) <span class="text-danger">*</span> @endif</label>
                {!! Form::file('image', ['class'=>'form-control', 'disabled'=>$disabled,"accept"=>"image/*"]) !!}
                @if ($errors->has("image"))
                    <span class="form-text text-danger">{{$errors->first('image')}}</span>
                @endif
            </div>
            <div class="col-lg-6">
                <label>{{__('Video')}} @if(!$preview) <span class="text-danger">*</span> @endif </label>
                {!! Form::file('video', ['class'=>'form-control', 'disabled'=>$disabled,"accept"=>"video/*"]) !!}
                @if ($errors->has("video"))
                    <span class="form-text text-danger">{{$errors->first('video')}}</span>
                @endif
            </div>
            <div class="col-lg-6">
                <label>{{__('Document')}}</label>
                {!! Form::file('doc', ['class'=>'form-control', 'disabled'=>$disabled,"accept"=>".xlsx, .xls, .pdf,.csv,.docx"]) !!}
                @if ($errors->has("doc"))
                    <span class="form-text text-danger">{{$errors->first('doc')}}</span>
                @endif
            </div>
        @endif
        @if($preview)
            @foreach ($project->files as $file)
            <div class="col-lg-6">
                 @if($file->mime == "image")
                        <div class="image">
                            <label for="image">{{__("image")}}</label><br>
                            <img src="{{$file->base . $file->name}}" alt="" class="img-thumbnail" id="image" height="250" width="400">
                        </div>
                    @elseif ($file->mime == "video")
                        <div class="video">
                            <label for="vieo">{{__("video")}}</label><br>
                            <div class="embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="{{$file->base . $file->name}}" allowfullscreen ></iframe>
                            </div>
                        </div>
                    @else
                        <div class="doc">
                            <label for="doc">{{__("Document")}}</label><br>
                            <a href="{{$file->base . $file->name}}" class="btn btn-primary">{{__("Download Document!")}}</a>
                        </div>
                @endif
            </div>
            @endforeach


        @endif
    </div>
</div>

resources/views/projects/index.blade.php
@extends('layouts.app', ['title' => $title ?? ''])

@section('content')

<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
</div>


    <div class="container-fluid mt-2">
        @include("layouts.includes.messages")
            <div class="card bg-secondary shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">{{__("Projects")}}</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="{{route("project.create")}}" class="btn btn-sm btn-primary">{{__("Create Project")}}</a>
                        </div>
                    </div>
                </div>
                <div style="padding: 10px">
                    <div class="table-responsive p-10">
                        <div class="table-responsive">
                            {!! $dataTable->table([
                                'class'=>'table align-items-center table-flush'
                            ],true)!!}
                        </div>
                    </div>
                </div>
            </div>
    </div>


@endsection

@push('js')

    {!! $dataTable->scripts() !!}

    <!-- Datatables buttons -->
    <script src="{{asset("plugins/datatables/checkbox.js")}}"></script>
    <script>
        delete_all();
    </script>
    <script src="{{asset("plugins/datatables/jquery.dataTables.min.js")}}"></script>
    <script src="{{asset("plugins/datatables-bs4/js/dataTables.bootstrap4.min.js")}}"></script>
    <script src="{{asset("plugins/datatables-responsive/js/dataTables.responsive.min.js")}}"></script>
    <script src="{{asset("plugins/datatables-responsive/js/responsive.bootstrap4.min.js")}}"></script>
    <script src="{{asset("plugins/vendor/datatables/buttons.server-side.js")}}"></script>
    <script src="{{asset("plugins/datatables-buttons/dataTables.buttons.min.js")}}"></script>
    <script src="{{asset("plugins/vendor/datatables/buttons.server-side.js")}}"></script>

@endpush
@push('css')
    <link rel="stylesheet" href="{{asset("plugins/datatables-buttons/css/buttons.bootstrap4.min.css")}}">
    <link rel="stylesheet" href="{{asset("plugins/datatables-responsive/css/responsive.bootstrap4.min.css")}}">
    <link rel="stylesheet" href="{{asset("plugins/datatables-bs4/css/dataTables.bootstrap4.min.css")}}">
@endpush

resources/views/projects/show.blade.php
@extends('layouts.app', ['title' => $title ?? ''])

@section('content')

<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
</div>

<div class="container-fluid mt--7">
    <div class="card bg-secondary shadow">
        <div class="kt-portlet__body">
            {!! Form::model($project,['class'=>'kt-form kt-form--labe-right','id'=>'kt_form']) !!}
            <div class="kt-portlet__head kt-portlet__head--lg">
                @include("layouts.includes.form_button",['disabled'=>true,"route"=>"project",'id'=>$project->id])
            </div>
                @include('projects.form', ['disabled'=>true,'preview'=>true])
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection