routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController')->middleware(['role:superadministrator']);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
    Route::get('map', function () {return view('pages.maps');})->name('map');
    Route::get('icons', function () {return view('pages.icons');})->name('icons');
    Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::resource("project","App\Http\Controllers\ProjectController");
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Project extends Model
{
    use HasFactory;
    protected $table="projects";
    protected $fillable=[
        "name",
        "desc",
        "url",
        "status",
        "user_id",
    ];
    const FILES_PATH_BASE="Project";
    const STATUS=['active'=>'active', 'incomplete'=>'incomplete', 'ongoing'=> 'ongoing','stuck'=>'stuck'];
    public function files(){
        return $this->morphMany(File::class,"fileable");
    }
    public function image(){
        return $this->files()->where("mime","image")->first();
    }
    public function video(){
        return $this->files()->where("mime","video")->first();
    }
    public function doc(){
        return $this->files()->where("mime","doc")->first();
    }
    public function user(){
        return $this->belongsTo(File::class,"user_id");
    }
    public static function files_attach($request,$project=null,$update=false){

        if($request->has("image") && !is_null($request->image)){
            upload_file($request->file('image'),Project::FILES_PATH_BASE,$project,'image');
            if($update){
                delete_file($project->image());
            }

        }
        if($request->has("video") && !is_null($request->video)){
            upload_file($request->file('video'),Project::FILES_PATH_BASE,$project,'video');
            if($update){
                delete_file($project->video());
            }
        }
        if($request->has("doc") && !is_null($request->doc)){
            upload_file($request->file('doc'),Project::FILES_PATH_BASE,$project,'doc');
            if($update){
                delete_file($project->doc());
            }
        }
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use App\DataTables\ProjectDatatable;
use App\Http\Requests\StoreProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Models\File;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()

    {
        $this->authorizeResource(Project::class, 'project');
    }
    public function index(ProjectDatatable $project)
    {

        $title=__('Project Management');
        return  $project->render("projects.index",compact("title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title=__('Create Project');
        $status=Project::STATUS;
        return view("projects.create",compact("title","status"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProjectRequest $request)
    {
        $request->validated();
        $project=Project::create(array_merge(["user_id"=>auth()->id()],$request->all()));
        Project::files_attach($request,$project);
        session()->flash('created',__("Changes has been Created successfully"));
        if(auth()->user()->hasRole("user")){
            return redirect()->to(route("project.index")."?user=".auth()->id());
        }
        return redirect()->route("project.index");
    }

/**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {

        $title=__('Show Project');
        $status=Project::STATUS;
        return view("projects.show",compact("project",'status'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $title=__('Edit Project');
        $status=Project::STATUS;
        return view("projects.edit",compact("project",'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProjectRequest $request, Project $project)
    {
        $request->validated();
        $project->update($request->all());
        Project::files_attach($request,$project,true);
        session()->flash('created',__("Changes has been Updated successfully"));
        if(auth()->user()->hasRole("user")){
            return redirect()->to(route("project.index")."?user=".auth()->id());
        }
        return redirect()->route("project.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        foreach($project->files as $file){
            delete_file($file);
            $file->delete();
        }
        $project->delete();
        session()->flash('deleted',__("Changes has been Deleted successfully"));
        return redirect()->route("project.index");
    }
}

resources/views/projects/btn/action.blade.php
@permission("projects-update")
    <a href="{{ route('project.edit', ['project' => $id]) }}" class="btn btn-sm btn-success btn-icon ">
        <i class=" fa fa-edit"></i>
    </a>
@endpermission
@permission("projects-read")
<a href="{{route('project.show',['project'=>$id])}}"  target='_blank' class="btn btn-sm btn-primary btn-icon ">
    <i class="ni ni-badge text-white"></i>
</a>
@endpermission
@permission("projects-delete")
<!-- Trigger the modal with a button -->
<a href="javascript:;" class="btn btn-sm btn-danger btn-icon" title="Delete" data-toggle="modal"
    data-target="#myModal{{ $id }}">
    <i class="fa fa-trash"></i>
</a>

<!-- Modal -->
<div id="myModal{{ $id }}" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@lang("Delete Record")</h4>
            </div>
            {!! Form::open(['route' => ['project.destroy', $id], 'method' => 'delete']) !!}
            <div class="modal-body">
                <p>{{ __('Are you sure you want delete this item  ? ') }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">@lang("Close")</button>
                {!! Form::submit(__('Yes'), ['class' => 'btn btn-danger']) !!}
            </div>
        </div>

    </div>
</div>
@endpermission

resources/views/projects/btn/checkbox.blade.php
<label class="checkbox checkbox-single">
    <input type="checkbox" name="item[]" class='item_checkbox' value="{{$id}}">
    <span></span>
</label>

resources/views/projects/btn/user.blade.php
<div class="text-center">
    <a href="{{route('user.show',['user'=>$user->id])}}"  target='_blank' class="btn btn-sm btn-warning btn-icon ">
        <i class="fa fa-user"></i>
    </a>
</div>