routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController')->middleware(['role:superadministrator']);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
    Route::get('map', function () {return view('pages.maps');})->name('map');
    Route::get('icons', function () {return view('pages.icons');})->name('icons');
    Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::resource("project","App\Http\Controllers\ProjectController");
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'phone',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function projects(){
        return $this->hasMany(Project::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UserDatatable;
use App\Models\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    public function index(UserDatatable $user)
    {
        $tite=__("User Management");
        return $user->render('users.index',compact("tite"));
    }
     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title=__('Create User');
        return view("users.create",compact("title"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $request->validated();
        User::create($request->all());
        session()->flash('created',__("Changes has been Created successfully"));
        return redirect()->route("user.index");
    }

/**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $title=__('Show User');
        return view("users.show",compact("user"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $title=__('Edit User');
        return view("users.edit",compact("user",));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        $request->validated();
        $user->update($request->all());
        session()->flash('created',__("Changes has been Updated successfully"));
        return redirect()->route("user.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->projects()->delete();
        $user->delete();
        session()->flash('deleted',__("Changes has been Deleted successfully"));
        return redirect()->route("user.index");
    }
}

resources/views/users/btn/action.blade.php
<a href="{{ route('user.edit', ['user' => $id]) }}" class="btn btn-sm btn-success btn-icon ">
    <i class=" fa fa-edit"></i>
</a>
<a href="{{route('user.show',['user'=>$id])}}"  target='_blank' class="btn btn-sm btn-primary btn-icon ">
    <i class="ni ni-badge text-white"></i>
</a>
<!-- Trigger the modal with a button -->
<a href="javascript:;" class="btn btn-sm btn-danger btn-icon" title="Delete" data-toggle="modal"
    data-target="#myModal{{ $id }}">
    <i class="fa fa-trash"></i>
</a>


<!-- Modal -->
<div id="myModal{{ $id }}" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@lang("Delete Record")</h4>
            </div>
            {!! Form::open(['route' => ['user.destroy', $id], 'method' => 'delete']) !!}
            <div class="modal-body">
                <p>{{ __('Are you sure you want delete this item  ? ') }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">@lang("Close")</button>
                {!! Form::submit(__('Yes'), ['class' => 'btn btn-danger']) !!}
            </div>
        </div>

    </div>
</div>

resources/views/users/btn/checkbox.blade.php
<label class="checkbox checkbox-single">
    <input type="checkbox" name="item[]" class='item_checkbox' value="{{$id}}">
    <span></span>
</label>